---
steps:

  - block

  - label: ':cloudsmith: Build image and push to Cloudsmith'
    command: './scripts/build-and-push-to-cloudsmith.sh'
    agents:
      queue: fma-dev

  - wait

  - label: ":k8s: Deploy to Europa Pre-Prod"
    command: './scripts/deploy.sh'
    agents:
      queue: europa-preprod-fma